# Generated by Django 5.2.17 on 2026-08-21 05:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0004_add_user_to_supplier'),
        ('order', '0006_alter_orderstatushistory_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین به\u200cروزرسانی')),
                ('supplier', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ledger', to='catalog.supplier', verbose_name='تأمین\u200cکننده')),
            ],
            options={
                'verbose_name': 'دفتر حساب تأمین\u200cکننده',
                'verbose_name_plural': 'دفاتر حساب تأمین\u200cکنندگان',
            },
        ),
        migrations.CreateModel(
            name='Settlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='مبلغ تسویه')),
                ('status', models.CharField(choices=[('PENDING', 'در انتظار'), ('COMPLETED', 'تکمیل شده'), ('REJECTED', 'رد شده')], default='PENDING', max_length=20, verbose_name='وضعیت')),
                ('notes', models.TextField(blank=True, verbose_name='یادداشت')),
                ('settled_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ تسویه')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_settlements', to=settings.AUTH_USER_MODEL, verbose_name='ثبت\u200cکننده')),
                ('ledger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlements', to='finance.supplierledger', verbose_name='دفتر حساب')),
            ],
            options={
                'verbose_name': 'تسویه حساب',
                'verbose_name_plural': 'تسویه حساب\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupplierTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('SALE', 'فروش'), ('SETTLEMENT', 'تسویه'), ('ADJUSTMENT', 'اصلاحیه دستی'), ('REFUND', 'مرجوعی')], max_length=20, verbose_name='نوع تراکنش')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='مبلغ')),
                ('description', models.CharField(blank=True, max_length=500, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_supplier_transactions', to=settings.AUTH_USER_MODEL, verbose_name='ثبت\u200cکننده')),
                ('ledger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='finance.supplierledger', verbose_name='دفتر حساب')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_transactions', to='order.order', verbose_name='سفارش')),
            ],
            options={
                'verbose_name': 'تراکنش تأمین\u200cکننده',
                'verbose_name_plural': 'تراکنش\u200cهای تأمین\u200cکنندگان',
                'ordering': ['-created_at'],
            },
        ),
    ]
