# Generated by Django 5.2.17 on 2026-08-28 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplierledger',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='suppliertransaction',
            name='ledger',
        ),
        migrations.RemoveField(
            model_name='suppliertransaction',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='suppliertransaction',
            name='order',
        ),
        migrations.DeleteModel(
            name='Settlement',
        ),
        migrations.DeleteModel(
            name='SupplierLedger',
        ),
        migrations.DeleteModel(
            name='SupplierTransaction',
        ),
    ]
