# Generated by Django 5.2.17 on 2026-08-20 15:33

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0003_alter_inventorytransaction_reference_id'),
        ('order', '0006_alter_orderstatushistory_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone', models.CharField(db_index=True, max_length=11, validators=[django.core.validators.RegexValidator(message='شماره موبایل باید ۱۱ رقم و با ۰۹ شروع شود', regex='^09[0-9]{9}$')], verbose_name='شماره موبایل')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='نام (اختیاری)')),
                ('status', models.CharField(choices=[('PENDING', 'در انتظار موجودی'), ('NOTIFIED', 'اطلاع\u200cرسانی شد'), ('CONVERTED', 'تبدیل به خرید'), ('CANCELLED', 'لغو شد')], db_index=True, default='PENDING', max_length=20, verbose_name='وضعیت')),
                ('notified_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان اطلاع\u200cرسانی')),
                ('notification_method', models.CharField(blank=True, help_text='SMS, Email, etc.', max_length=20, verbose_name='روش اطلاع\u200cرسانی')),
                ('converted_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان تبدیل به خرید')),
                ('admin_notes', models.TextField(blank=True, verbose_name='یادداشت ادمین')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='converted_from_leads', to='order.order', verbose_name='سفارش تبدیل\u200cشده')),
                ('product', models.ForeignKey(blank=True, help_text='اختیاری - اگر خالی باشد، سرنخ عمومی است', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='catalog.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'سرنخ',
                'verbose_name_plural': 'سرنخ\u200cها',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['phone', 'status'], name='leads_lead_phone_b71730_idx'), models.Index(fields=['product', 'status'], name='leads_lead_product_508851_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'PENDING')), fields=('phone', 'product'), name='unique_pending_lead_per_phone_product')],
            },
        ),
    ]
