# Generated by Django 5.2.17 on 2026-08-31 19:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitorLead',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ip', models.GenericIPAddressField(db_index=True, unique=True, verbose_name='IP')),
                ('country', models.CharField(blank=True, max_length=60, verbose_name='کشور')),
                ('city', models.CharField(blank=True, max_length=60, verbose_name='شهر')),
                ('isp', models.CharField(blank=True, max_length=120, verbose_name='ISP/اپراتور')),
                ('is_vpn', models.BooleanField(default=False, verbose_name='مشکوک به VPN')),
                ('device', models.CharField(blank=True, max_length=20, verbose_name='دستگاه')),
                ('channel_first', models.CharField(blank=True, max_length=40, verbose_name='کانال ورود')),
                ('channels', models.JSONField(blank=True, default=list, verbose_name='همهٔ کانال\u200cها')),
                ('first_seen', models.DateTimeField(blank=True, null=True, verbose_name='اولین بازدید')),
                ('last_seen', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='آخرین بازدید')),
                ('sessions_count', models.PositiveIntegerField(default=0, verbose_name='تعداد سشن')),
                ('page_views', models.PositiveIntegerField(default=0, verbose_name='تعداد ویو')),
                ('stage', models.CharField(choices=[('HOME', 'بازدید ساده'), ('PRODUCT', 'مشاهده محصول'), ('CART', 'سبد خرید'), ('CHECKOUT', 'تسویه حساب'), ('PAYMENT', 'صفحه پرداخت'), ('CONVERTED', 'خرید موفق')], db_index=True, default='HOME', max_length=12, verbose_name='مرحلهٔ قیف')),
                ('stage_rank', models.PositiveSmallIntegerField(db_index=True, default=1)),
                ('is_hot', models.BooleanField(default=False, verbose_name='سرنخ داغ')),
                ('actions', models.JSONField(blank=True, default=dict, verbose_name='اقدام\u200cها (POST)')),
                ('order_refs', models.CharField(blank=True, max_length=200, verbose_name='سفارش\u200cها در لاگ')),
                ('orders_matched', models.JSONField(blank=True, default=list, verbose_name='سفارش\u200cهای در DB')),
                ('sessions', models.JSONField(blank=True, default=list, verbose_name='جزئیات سشن\u200cها')),
                ('status', models.CharField(choices=[('NEW', 'جدید (نیاز به پیگیری)'), ('CONTACTED', 'تماس گرفته شد'), ('NOANSWER', 'بدون پاسخ'), ('LOST', 'از دست رفته'), ('BUYER', 'خریدار'), ('JUNK', 'تست/نامعتبر')], db_index=True, default='NEW', max_length=12, verbose_name='وضعیت CRM')),
                ('admin_notes', models.TextField(blank=True, verbose_name=' یادداشت ادمین')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
            ],
            options={
                'verbose_name': 'سرنخ بازدید',
                'verbose_name_plural': 'سرنخ\u200cهای بازدید',
                'ordering': ['-last_seen'],
                'indexes': [models.Index(fields=['stage', 'status'], name='leads_visit_stage_089f1b_idx'), models.Index(fields=['-last_seen'], name='leads_visit_last_se_91d9cc_idx')],
            },
        ),
    ]
