# Generated by Django 5.2.17 on 2026-08-31 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_visitorlead'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitorlead',
            name='link_code',
            field=models.CharField(blank=True, db_index=True, max_length=8, verbose_name='کد اتصال واتساپ'),
        ),
        migrations.AddField(
            model_name='visitorlead',
            name='name',
            field=models.CharField(blank=True, max_length=100, verbose_name='نام'),
        ),
        migrations.AddField(
            model_name='visitorlead',
            name='phone',
            field=models.CharField(blank=True, db_index=True, max_length=15, verbose_name='شماره تماس'),
        ),
    ]
