# Generated by Django 5.2.17 on 2026-08-16 09:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_key', models.CharField(blank=True, max_length=100, verbose_name='شناسه نشست (برای مهمان)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'سبد خرید',
                'verbose_name_plural': 'سبدهای خرید',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='تعداد')),
                ('unit_price_at_add', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='قیمت واحد در لحظه افزودن')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='order.cart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='catalog.product')),
            ],
            options={
                'verbose_name': 'کالای سبد',
                'verbose_name_plural': 'کالاهای سبد',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_number', models.CharField(blank=True, max_length=20, unique=True, verbose_name='شماره سفارش')),
                ('session_key', models.CharField(blank=True, max_length=100, verbose_name='شناسه نشست (برای مهمان)')),
                ('status', models.CharField(choices=[('DRAFT', 'پیش\u200cنویس'), ('PENDING', 'در انتظار پرداخت'), ('PAID', 'پرداخت شده'), ('PROCESSING', 'در حال پردازش'), ('SHIPPED', 'ارسال شده'), ('DELIVERED', 'تحویل داده شده'), ('CANCELLED', 'لغو شده')], default='DRAFT', max_length=20)),
                ('guest_name', models.CharField(blank=True, max_length=150, verbose_name='نام خریدار (مهمان)')),
                ('guest_phone', models.CharField(blank=True, max_length=20, verbose_name='تلفن تماس (مهمان)')),
                ('guest_address', models.TextField(blank=True, verbose_name='آدرس کامل (مهمان)')),
                ('guest_postal_code', models.CharField(blank=True, max_length=20, verbose_name='کد پستی (مهمان)')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='جمع کل کالاها')),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='هزینه ارسال')),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='مبلغ نهایی')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'سفارش',
                'verbose_name_plural': 'سفارشات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price_at_purchase', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product_name_snapshot', models.CharField(max_length=200, verbose_name='نام محصول در لحظه خرید')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='order.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'قلم سفارش',
                'verbose_name_plural': 'اقلام سفارش',
            },
        ),
    ]
