# Generated by Django 5.2.17 on 2026-08-16 09:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='مبلغ پرداختی')),
                ('status', models.CharField(choices=[('PENDING', 'در انتظار پرداخت'), ('SUCCESS', 'پرداخت موفق'), ('FAILED', 'پرداخت ناموفق'), ('CANCELLED', 'لغو شده توسط کاربر')], default='PENDING', max_length=20)),
                ('gateway', models.CharField(choices=[('MOCK', 'درگاه شبیه\u200cسازی شده'), ('ZARINPAL', 'زرین\u200cپال'), ('IDPAY', 'آیدی\u200cپی')], default='MOCK', max_length=20)),
                ('authority', models.CharField(blank=True, max_length=100, verbose_name='شناسه یکتا در درگاه')),
                ('ref_id', models.CharField(blank=True, max_length=100, verbose_name='کد پیگیری (پس از پرداخت)')),
                ('gateway_response', models.JSONField(blank=True, null=True, verbose_name='پاسخ کامل درگاه')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='order.order')),
            ],
            options={
                'verbose_name': 'تراکنش پرداخت',
                'verbose_name_plural': 'تراکنش\u200cهای پرداخت',
                'ordering': ['-created_at'],
            },
        ),
    ]
