# Generated by Django 5.2.17 on 2026-08-16 09:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_payment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50, verbose_name='عنوان آدرس')),
                ('address_type', models.CharField(choices=[('HOME', 'منزل'), ('WORK', 'محل کار'), ('OTHER', 'سایر')], default='HOME', max_length=10)),
                ('full_name', models.CharField(max_length=150, verbose_name='نام و نام خانوادگی گیرنده')),
                ('phone', models.CharField(max_length=20, verbose_name='شماره تماس گیرنده')),
                ('province', models.CharField(max_length=50, verbose_name='استان')),
                ('city', models.CharField(max_length=50, verbose_name='شهر')),
                ('postal_code', models.CharField(max_length=20, verbose_name='کد پستی')),
                ('detailed_address', models.TextField(verbose_name='آدرس دقیق')),
                ('is_default', models.BooleanField(default=False, verbose_name='آدرس پیش\u200cفرض')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'آدرس',
                'verbose_name_plural': 'آدرس\u200cها',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
    ]
