# Generated by Django 5.2.17 on 2026-08-18 15:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_address'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='admin_notes',
            field=models.TextField(blank=True, verbose_name='یادداشت ادمین (در صورت رد یا تایید)'),
        ),
        migrations.AddField(
            model_name='payment',
            name='receipt_image',
            field=models.ImageField(blank=True, null=True, upload_to='payment_receipts/%Y/%m/', verbose_name='تصویر رسید پرداخت'),
        ),
        migrations.AddField(
            model_name='payment',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان تایید'),
        ),
        migrations.AddField(
            model_name='payment',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_payments', to=settings.AUTH_USER_MODEL, verbose_name='تاییدکننده (ادمین)'),
        ),
        migrations.AddField(
            model_name='payment',
            name='sender_card_last4',
            field=models.CharField(blank=True, max_length=4, verbose_name='۴ رقم آخر کارت فرستنده'),
        ),
        migrations.AddField(
            model_name='payment',
            name='transfer_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان واریز'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='هزینه ارسال (در قیمت نهایی نهفته)'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='gateway',
            field=models.CharField(choices=[('MANUAL', 'کارت\u200cبه\u200cکارت (دستی)'), ('MOCK', 'درگاه شبیه\u200cسازی شده'), ('ZARINPAL', 'زرین\u200cپال'), ('IDPAY', 'آیدی\u200cپی')], default='MANUAL', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'در انتظار پرداخت'), ('PENDING_REVIEW', 'در انتظار تایید ادمین'), ('SUCCESS', 'پرداخت موفق'), ('FAILED', 'پرداخت ناموفق'), ('CANCELLED', 'لغو شده توسط کاربر')], default='PENDING', max_length=20),
        ),
    ]
