# Generated by Django 5.2.17 on 2026-08-20 10:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_payment_admin_notes_payment_receipt_image_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ تحویل'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipped_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ ارسال'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_method',
            field=models.CharField(blank=True, help_text='پست، تیپاکس، باربری، پیک', max_length=50, verbose_name='روش ارسال'),
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_code',
            field=models.CharField(blank=True, max_length=100, verbose_name='کد رهگیری پست/باربری'),
        ),
        migrations.CreateModel(
            name='OrderStatusHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('ORDER_CREATED', 'Order Created'), ('PENDING_PAYMENT', 'Pending Payment'), ('PAYMENT_SUBMITTED', 'Payment Submitted'), ('PAYMENT_CONFIRMED', 'Payment Confirmed'), ('PAYMENT_REJECTED', 'Payment Rejected'), ('PROCESSING', 'Processing'), ('SHIPPED', 'Shipped'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], max_length=30, verbose_name='Status')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('tracking_code', models.CharField(blank=True, max_length=100, verbose_name='Tracking Code')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Changed By')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='order.order')),
            ],
            options={
                'verbose_name': 'Order Status History',
                'verbose_name_plural': 'Order Status Histories',
                'ordering': ['created_at'],
            },
        ),
    ]
