# Generated by Django 5.2.17 on 2026-08-20 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_order_delivered_at_order_shipped_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderstatushistory',
            name='status',
            field=models.CharField(choices=[('ORDER_CREATED', 'سفارش ثبت شد'), ('PENDING_PAYMENT', 'در انتظار پرداخت'), ('PAYMENT_SUBMITTED', 'پرداخت ارسال شد'), ('PAYMENT_CONFIRMED', 'پرداخت تایید شد'), ('PAYMENT_REJECTED', 'پرداخت رد شد'), ('PROCESSING', 'در حال آماده\u200cسازی'), ('SHIPPED', 'ارسال شد'), ('DELIVERED', 'تحویل داده شد'), ('CANCELLED', 'لغو شد')], max_length=30, verbose_name='Status'),
        ),
    ]
