# Generated by Django 5.2.17 on 2026-08-23 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_productvariant'),
        ('order', '0006_alter_orderstatushistory_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='catalog.productvariant', verbose_name='واریانت انتخابی'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='catalog.productvariant', verbose_name='واریانت خریداری\u200cشده'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='variant_title',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='عنوان واریانت در لحظه خرید'),
        ),
    ]
