# Generated by Django 5.2.17 on 2026-08-24 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_cartitem_variant_orderitem_variant_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=50, verbose_name='نام بانک')),
                ('card_number', models.CharField(help_text='۱۶ رقمی — جداکننده لازم نیست، خودکار تمیز می\u200cشود', max_length=24, verbose_name='شماره کارت')),
                ('card_holder', models.CharField(max_length=100, verbose_name='نام صاحب حساب')),
                ('iban', models.CharField(blank=True, default='', help_text='اختیاری — با یا بدون IR', max_length=30, verbose_name='شماره شبا')),
                ('label', models.CharField(blank=True, default='', help_text='مثلاً: کارت اصلی فروشگاه (اختیاری)', max_length=60, verbose_name='برچسب نمایشی')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'حساب بانکی مقصد',
                'verbose_name_plural': 'حساب\u200cهای بانکی مقصد',
                'ordering': ['sort_order', 'created_at'],
            },
        ),
    ]
