# Generated by Django 5.2.17 on 2026-08-24 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_bankaccount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'در انتظار پرداخت'), ('PENDING_REVIEW', 'در انتظار بررسی و تایید'), ('SUCCESS', 'پرداخت موفق'), ('FAILED', 'پرداخت ناموفق'), ('CANCELLED', 'لغو شده توسط کاربر')], default='PENDING', max_length=20),
        ),
    ]
