# Generated by Django 5.2.17 on 2026-08-25 13:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_product_compare_at_price_product_curation_story_and_more'),
        ('order', '0010_order_expires_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fulfiller', models.CharField(choices=[('SUPPLIER', 'تامین\u200cکننده'), ('RIHAN', 'ریهان (ارسال داخلی)')], default='SUPPLIER', max_length=10, verbose_name='ارسال توسط')),
                ('status', models.CharField(choices=[('NEW', 'در انتظار ارسال'), ('SHIPPED', 'ارسال شده'), ('DELIVERED', 'تحویل داده شد'), ('CANCELED', 'لغو شده')], db_index=True, default='NEW', max_length=10, verbose_name='وضعیت')),
                ('carrier', models.CharField(choices=[('POST', 'پست پیشتاز'), ('TIPAX', 'تیپاکس'), ('CHAPAR', 'چاپار'), ('OTHER', 'سایر')], default='POST', max_length=10, verbose_name='شرکت حمل')),
                ('tracking_code', models.CharField(blank=True, db_index=True, default='', max_length=40, verbose_name='کد رهگیری')),
                ('sent_to_supplier_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان اولین اطلاع\u200cرسانی')),
                ('last_notified_at', models.DateTimeField(blank=True, null=True, verbose_name='آخرین یادآوری')),
                ('supplier_notified_count', models.PositiveSmallIntegerField(default=0, verbose_name='تعداد پیامک ارسالی به تامین\u200cکننده')),
                ('shipped_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان ارسال')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان تحویل')),
                ('notes', models.TextField(blank=True, default='', verbose_name='یادداشت هماهنگی ارسال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='به\u200cروزرسانی')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='order.order', verbose_name='سفارش')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipments', to='catalog.supplier', verbose_name='تامین\u200cکننده')),
            ],
            options={
                'verbose_name': 'مرسوله',
                'verbose_name_plural': 'مرسوله\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('SUPPLIER_ASSIGN', 'پیامک سفارش جدید به تامین\u200cکننده'), ('CUSTOMER_SHIPPED', 'پیامک کد رهگیری به مشتری'), ('SYSTEM', 'سیستمی')], db_index=True, max_length=20, verbose_name='نوع اطلاع\u200cرسانی')),
                ('recipient', models.CharField(blank=True, max_length=20, verbose_name='گیرنده')),
                ('success', models.BooleanField(default=False, verbose_name='ارسال موفق')),
                ('detail', models.CharField(blank=True, default='', max_length=250, verbose_name='جزئیات / سرویس\u200cدهنده')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='order.order', verbose_name='سفارش')),
                ('shipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='order.shipment', verbose_name='مرسوله')),
            ],
            options={
                'verbose_name': 'لاگ اطلاع\u200cرسانی',
                'verbose_name_plural': 'لاگ اطلاع\u200cرسانی\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShipmentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='تعداد')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipment_items', to='order.orderitem', verbose_name='قلم سفارش')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='order.shipment', verbose_name='مرسوله')),
            ],
            options={
                'verbose_name': 'قلم مرسوله',
                'verbose_name_plural': 'اقلام مرسوله',
                'constraints': [models.UniqueConstraint(fields=('shipment', 'order_item'), name='uniq_shipment_order_item')],
            },
        ),
    ]
