# Generated by Django 5.2.17 on 2026-08-26 02:11

import src.core.upload_validation
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_shipment_notificationlog_shipmentitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='receipt_image',
            field=models.ImageField(blank=True, null=True, upload_to='payment_receipts/%Y/%m/', validators=[src.core.upload_validation.validate_upload_image], verbose_name='تصویر رسید پرداخت'),
        ),
    ]
