# Generated by Django 5.2.17 on 2026-08-27 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_alter_payment_receipt_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='other_carrier_name',
            field=models.CharField(blank=True, default='', help_text='وقتی شرکت حمل «سایر» انتخاب شد، نام شرکت/سرویس را بنویسید', max_length=100, verbose_name='نام شرکت حمل (حالت سایر)'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='other_carrier_person',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='نام ارسال\u200cکننده / راننده'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='other_carrier_phone',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='شماره تماس حمل\u200cکننده'),
        ),
    ]
