# Generated by Django 5.2.17 on 2026-08-28 06:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_shipment_other_carrier_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='settlement_status',
            field=models.CharField(choices=[('NONE', 'بدون نیاز (فروش خود ادمین)'), ('PENDING', 'در انتظار تسویه تامین\u200cکننده'), ('PARTIAL', 'تسویه\u200cشده بخشی'), ('SETTLED', 'تسویه با تامین\u200cکننده')], db_index=True, default='NONE', max_length=10, verbose_name='وضعیت تسویه تامین\u200cکننده'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='unit_cost_at_purchase',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='قیمت خرید واحد در لحظه خرید'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='other_costs',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='سایر هزینه\u200cها (بسته\u200cبندی/برچسب/…)'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='other_costs_note',
            field=models.CharField(blank=True, default='', max_length=250, verbose_name='توضیح سایر هزینه\u200cها'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='other_paid_by',
            field=models.CharField(choices=[('RIHAN', 'ریهان'), ('SUPPLIER', 'تامین\u200cکننده')], default='SUPPLIER', max_length=10, verbose_name='سایر هزینه\u200cها پرداخت\u200cشده توسط'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='post_cost',
            field=models.DecimalField(decimal_places=0, default=0, help_text='هزینه واقعی ارسال این مرسوله — دستی وارد می\u200cشود', max_digits=12, verbose_name='هزینه پست/باربری (تومان)'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='post_paid_by',
            field=models.CharField(choices=[('RIHAN', 'ریهان'), ('SUPPLIER', 'تامین\u200cکننده')], default='SUPPLIER', help_text='اگر تامین\u200cکننده پرداخت کرده باشد، در تسویه به او برگردانده می\u200cشود', max_length=10, verbose_name='هزینه پست پرداخت\u200cشده توسط'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='settled_amount',
            field=models.DecimalField(blank=True, decimal_places=0, editable=False, max_digits=12, null=True, verbose_name='مبلغ تسویه\u200cشده (snapshot)'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='settled_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='زمان تسویه'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='settled_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settled_shipments', to=settings.AUTH_USER_MODEL, verbose_name='تسویه\u200cکننده'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='settlement_note',
            field=models.CharField(blank=True, default='', max_length=250, verbose_name='یادداشت تسویه'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='settlement_status',
            field=models.CharField(choices=[('UNSETTLED', 'در انتظار تسویه'), ('SETTLED', 'تسویه شد')], db_index=True, default='UNSETTLED', max_length=10, verbose_name='وضعیت تسویه'),
        ),
    ]
