# Generated by Django 5.2.17 on 2026-08-29 08:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0014_order_settlement_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('PAYMENT_CONFIRMED', 'پرداخت تایید شد'), ('PROCESSING', 'در حال آماده\u200cسازی'), ('SHIPPED', 'سفارش ارسال شد'), ('DELIVERED', 'سفارش تحویل شد'), ('CANCELLED', 'سفارش لغو شد'), ('SUPPLIER_DELAY', 'هشدار تاخیر تامین\u200cکننده'), ('SYSTEM', 'سیستمی')], db_index=True, default='SYSTEM', max_length=30, verbose_name='نوع')),
                ('title', models.CharField(max_length=150, verbose_name='عنوان')),
                ('body', models.CharField(blank=True, default='', max_length=300, verbose_name='متن')),
                ('url', models.CharField(blank=True, default='', max_length=200, verbose_name='لینک')),
                ('is_read', models.BooleanField(db_index=True, default=False, verbose_name='خوانده\u200cشده')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='زمان')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_notifications', to='order.order', verbose_name='سفارش')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='گیرنده')),
            ],
            options={
                'verbose_name': 'اعلان کاربر',
                'verbose_name_plural': 'اعلان\u200cهای کاربران',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read'], name='order_usern_recipie_c332a8_idx')],
            },
        ),
    ]
