# Generated by Django 5.2.17 on 2026-09-02 04:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0015_usernotification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True, verbose_name='کد')),
                ('kind', models.CharField(choices=[('percent', 'درصدی'), ('fixed', 'مبلغ ثابت (تومان)')], default='fixed', max_length=10, verbose_name='نوع تخفیف')),
                ('value', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='مقدار (درصد یا تومان)')),
                ('min_cart', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='حداقل مبلغ سبد (تومان)')),
                ('max_uses_total', models.PositiveIntegerField(default=0, verbose_name='سقف کل استفاده (0=بی\u200cنهایت)')),
                ('max_uses_per_user', models.PositiveIntegerField(default=1, verbose_name='سقف هر شماره (0=بی\u200cنهایت)')),
                ('used_count', models.PositiveIntegerField(default=0, editable=False, verbose_name='تعداد استفاده\u200cشده')),
                ('active', models.BooleanField(default=True, verbose_name='فعال')),
                ('starts_at', models.DateTimeField(blank=True, null=True, verbose_name='شروع')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='انقضا')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='یادداشت داخلی')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'کد تخفیف',
                'verbose_name_plural': 'کدهای تخفیف',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='مبلغ تخفیف'),
        ),
        migrations.AddField(
            model_name='order',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='order.coupon', verbose_name='کد تخفیف'),
        ),
        migrations.CreateModel(
            name='CouponUse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=15, verbose_name='تلفن استفاده\u200cکننده')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='مبلغ تخفیف')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uses', to='order.coupon')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupon_uses', to='order.order')),
            ],
            options={
                'verbose_name': 'استفاده از کد تخفیف',
                'verbose_name_plural': 'استفاده\u200cهای کدهای تخفیف',
            },
        ),
    ]
