# Generated by Django 5.0.14 on 2026-08-14 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveBigIntegerField(verbose_name='مبلغ تراکنش (تومان)')),
                ('gateway_type', models.CharField(choices=[('card_to_card', 'کارت\u200cبه\u200cکارت'), ('online_gateway', 'درگاه آنلاین')], default='card_to_card', max_length=30, verbose_name='روش پرداخت')),
                ('status', models.CharField(choices=[('pending', 'در انتظار واریز'), ('submitted', 'رسید ثبت\u200cشده / در حال بررسی'), ('verified', 'تأییدشده'), ('rejected', 'ردشده')], default='pending', max_length=30, verbose_name='وضعیت پرداخت')),
                ('receipt_image', models.ImageField(blank=True, null=True, upload_to='receipts/%Y/%m/', verbose_name='تصویر فیش واریزی')),
                ('transaction_reference', models.CharField(blank=True, max_length=100, verbose_name='شماره پیگیری / ارجاع')),
                ('card_last_four', models.CharField(blank=True, max_length=4, verbose_name='۴ رقم آخر کارت واریزکننده')),
                ('destination_card', models.CharField(default='۶۰۳۷-۹۹۷۵-۱۲۳۴-۵۶۷۸', max_length=50, verbose_name='شماره کارت مقصد')),
                ('admin_notes', models.TextField(blank=True, verbose_name='توضیحات و بررسی ادمین')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان تأیید')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین تغییر')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='orders.order', verbose_name='سفارش')),
            ],
            options={
                'verbose_name': 'پرداخت',
                'verbose_name_plural': 'پرداخت\u200cها',
                'ordering': ['-created_at'],
            },
        ),
    ]
