# Generated by Django 5.2.17 on 2026-08-20 12:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0003_alter_inventorytransaction_reference_id'),
        ('order', '0006_alter_orderstatushistory_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('guest_name', models.CharField(blank=True, max_length=100, verbose_name='Guest name')),
                ('guest_phone', models.CharField(blank=True, max_length=20, verbose_name='Guest phone (for token verification)')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='Rating (1-5 stars)')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='Title (optional)')),
                ('text', models.TextField(max_length=500, verbose_name='Review text (max 500 chars)')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Approved by admin')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Approval time')),
                ('admin_reply', models.TextField(blank=True, verbose_name='Admin reply')),
                ('guest_token', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='One-time token for guests')),
                ('token_expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Token expiration (7 days)')),
                ('token_used', models.BooleanField(default=False, verbose_name='Token has been used')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_reviews', to=settings.AUTH_USER_MODEL, verbose_name='Approved by')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='order.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='catalog.product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='Registered user')),
            ],
            options={
                'verbose_name': 'Review',
                'verbose_name_plural': 'Reviews',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['product', 'is_approved'], name='reviews_rev_product_99e47c_idx'), models.Index(fields=['order'], name='reviews_rev_order_i_a8ba91_idx')],
                'constraints': [models.UniqueConstraint(fields=('order',), name='unique_review_per_order')],
            },
        ),
    ]
