# Generated by Django 5.2.17 on 2026-08-25 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='display_anonymously',
            field=models.BooleanField(default=True, help_text='اگر روشن باشد، نام کاربر به\u200cصورت محرمانه (مثلاً «م. ح.» یا «خریدار تأییدشده») نمایش داده می\u200cشود.', verbose_name='نمایش ناشناس نام نظردهنده'),
        ),
    ]
