# Generated by Django 5.0.14 on 2026-08-15 11:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plugin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='مثلاً: M1, M2, catalog, orders', max_length=50, unique=True, verbose_name='نام ماژول')),
                ('display_name', models.CharField(help_text='مثلاً: کاتالوگ محصولات', max_length=100, verbose_name='نام نمایشی')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('version', models.CharField(default='1.0.0', max_length=20, verbose_name='نسخه')),
                ('status', models.CharField(choices=[('active', 'فعال'), ('inactive', 'غیرفعال'), ('error', 'خطا')], default='active', max_length=20, verbose_name='وضعیت')),
                ('is_system', models.BooleanField(default=False, help_text='ماژول\u200cهای سیستمی قابل غیرفعال\u200cسازی نیستند', verbose_name='سیستمی')),
                ('manifest_data', models.JSONField(blank=True, default=dict, verbose_name='داده\u200cهای manifest.yaml')),
                ('enabled_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ فعال\u200cسازی')),
                ('disabled_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ غیرفعال\u200cسازی')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'ماژول/پلاگین',
                'verbose_name_plural': 'ماژول\u200cها/پلاگین\u200cها',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FeatureFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='مثلاً: FEATURE_SMS_OTP_LOGIN', max_length=100, unique=True, verbose_name='نام flag')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('enabled', models.BooleanField(default=False, verbose_name='فعال')),
                ('category', models.CharField(blank=True, help_text='مثلاً: payment, auth, ui', max_length=50, verbose_name='دسته\u200cبندی')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='آخرین تغییر توسط')),
            ],
            options={
                'verbose_name': 'Feature Flag',
                'verbose_name_plural': 'Feature Flags',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AdminActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login', 'ورود'), ('logout', 'خروج'), ('create', 'ایجاد'), ('update', 'ویرایش'), ('delete', 'حذف'), ('approve', 'تأیید'), ('reject', 'رد'), ('enable', 'فعال\u200cسازی'), ('disable', 'غیرفعال\u200cسازی')], max_length=20, verbose_name='عملیات')),
                ('resource_type', models.CharField(help_text='مثلاً: Product, Order, User', max_length=50, verbose_name='نوع منبع')),
                ('resource_id', models.IntegerField(blank=True, null=True, verbose_name='شناسه منبع')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('old_value', models.JSONField(blank=True, default=dict, verbose_name='مقدار قبلی')),
                ('new_value', models.JSONField(blank=True, default=dict, verbose_name='مقدار جدید')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاریخ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_activities', to=settings.AUTH_USER_MODEL, verbose_name='ادمین')),
            ],
            options={
                'verbose_name': 'لاگ فعالیت ادمین',
                'verbose_name_plural': 'لاگ\u200cهای فعالیت ادمین',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='plugin_arch_user_id_34c121_idx'), models.Index(fields=['action', '-created_at'], name='plugin_arch_action_889f78_idx'), models.Index(fields=['resource_type', 'resource_id'], name='plugin_arch_resourc_27002e_idx')],
            },
        ),
        migrations.CreateModel(
            name='EventLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(db_index=True, max_length=50, verbose_name='نوع event')),
                ('level', models.CharField(choices=[('debug', 'Debug'), ('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('critical', 'Critical')], default='info', max_length=20, verbose_name='سطح')),
                ('message', models.TextField(verbose_name='پیام')),
                ('data', models.JSONField(blank=True, default=dict, verbose_name='داده\u200cهای اضافی')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاریخ')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'Event Log',
                'verbose_name_plural': 'Event Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event_type', '-created_at'], name='plugin_arch_event_t_85c3b1_idx'), models.Index(fields=['level', '-created_at'], name='plugin_arch_level_463ee9_idx')],
            },
        ),
        migrations.CreateModel(
            name='PluginHook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('order.created', 'ایجاد سفارش'), ('order.paid', 'پرداخت سفارش'), ('order.shipped', 'ارسال سفارش'), ('order.delivered', 'تحویل سفارش'), ('user.login', 'ورود کاربر'), ('user.register', 'ثبت\u200cنام کاربر'), ('product.created', 'ایجاد محصول'), ('product.updated', 'به\u200cروزرسانی محصول'), ('review.created', 'ایجاد نظر'), ('review.approved', 'تأیید نظر'), ('lead.created', 'ایجاد سرنخ'), ('inventory.low', 'موجودی کم')], max_length=50, verbose_name='نوع event')),
                ('handler_path', models.CharField(help_text='مثلاً: modules.catalog.hooks.on_product_created', max_length=200, verbose_name='مسیر handler')),
                ('priority', models.IntegerField(default=100, help_text='عدد کمتر = اولویت بالاتر', verbose_name='اولویت')),
                ('enabled', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plugin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hooks', to='plugin_arch.plugin', verbose_name='ماژول')),
            ],
            options={
                'verbose_name': 'Plugin Hook',
                'verbose_name_plural': 'Plugin Hooks',
                'ordering': ['event_type', 'priority'],
                'unique_together': {('plugin', 'event_type', 'handler_path')},
            },
        ),
    ]
