# Generated by Django 5.0.14 on 2026-08-15 11:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, verbose_name='نام کاربری')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('success', models.BooleanField(verbose_name='موفق')),
                ('failure_reason', models.CharField(blank=True, help_text='مثلاً: invalid_password, account_locked, user_not_found', max_length=100, verbose_name='دلیل شکست')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='زمان')),
            ],
            options={
                'verbose_name': 'تلاش ورود',
                'verbose_name_plural': 'تلاش\u200cهای ورود',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['username', '-timestamp'], name='rbac_logina_usernam_cbe9c8_idx'), models.Index(fields=['ip_address', '-timestamp'], name='rbac_logina_ip_addr_64ff7e_idx')],
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='مثلاً: catalog.view', max_length=100, unique=True, verbose_name='کد مجوز')),
                ('name', models.CharField(max_length=200, verbose_name='نام مجوز')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('module', models.CharField(help_text='مثلاً: catalog, orders, users', max_length=50, verbose_name='ماژول')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'مجوز',
                'verbose_name_plural': 'مجوزها',
                'ordering': ['module', 'code'],
                'indexes': [models.Index(fields=['module', 'code'], name='rbac_permis_module_37b03a_idx')],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='نام نقش')),
                ('display_name', models.CharField(max_length=100, verbose_name='نام نمایشی')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('is_system', models.BooleanField(default=False, help_text='نقش\u200cهای سیستمی قابل حذف نیستند', verbose_name='سیستمی')),
                ('session_duration_hours', models.IntegerField(default=8, help_text='طبق US-016: ۸ ساعت', verbose_name='مدت جلسه (ساعت)')),
                ('max_login_attempts', models.IntegerField(default=5, help_text='طبق US-016: ۵ بار', verbose_name='حداکثر تلاش ورود')),
                ('lockout_duration_minutes', models.IntegerField(default=15, help_text='طبق US-016: ۱۵ دقیقه', verbose_name='مدت قفل (دقیقه)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('permissions', models.ManyToManyField(blank=True, related_name='roles', to='rbac.permission', verbose_name='مجوزها')),
            ],
            options={
                'verbose_name': 'نقش',
                'verbose_name_plural': 'نقش\u200cها',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('failed_login_attempts', models.IntegerField(default=0, verbose_name='تلاش\u200cهای ناموفق ورود')),
                ('locked_until', models.DateTimeField(blank=True, null=True, verbose_name='قفل تا')),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='آخرین IP ورود')),
                ('last_login_user_agent', models.TextField(blank=True, verbose_name='آخرین User Agent')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('notes', models.TextField(blank=True, verbose_name='یادداشت\u200cها')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='users', to='rbac.role', verbose_name='نقش')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'پروفایل کاربر',
                'verbose_name_plural': 'پروفایل\u200cهای کاربران',
            },
        ),
    ]
