# Generated by Django 5.2.17 on 2026-08-19 16:13

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='شناسه')),
                ('site_name', models.CharField(blank=True, default='ریحان', max_length=100, verbose_name='نام سایت')),
                ('site_tagline', models.CharField(blank=True, default='', max_length=200, verbose_name='شعار سایت')),
                ('currency', models.CharField(blank=True, default='تومان', max_length=10, verbose_name='واحد پول')),
                ('primary_color', models.CharField(blank=True, default='#8B4513', max_length=20, verbose_name='رنگ اصلی')),
                ('font_family', models.CharField(blank=True, default='Vazir', max_length=50, verbose_name='فونت')),
                ('contact_phone', models.CharField(blank=True, default='', max_length=20, verbose_name='شماره تماس')),
                ('contact_address', models.TextField(blank=True, default='', verbose_name='آدرس')),
                ('support_hours', models.CharField(blank=True, default='11 صبح تا 7 عصر', max_length=50, verbose_name='ساعات پاسخگویی')),
                ('office_city', models.CharField(blank=True, default='تبریز', max_length=50, verbose_name='شهر دفتر')),
                ('office_province', models.CharField(blank=True, default='آذربایجان شرقی', max_length=50, verbose_name='استان دفتر')),
                ('bank_card_number', models.CharField(blank=True, default='', max_length=20, verbose_name='شماره کارت')),
                ('bank_card_holder', models.CharField(blank=True, default='', max_length=100, verbose_name='صاحب کارت')),
                ('low_stock_threshold', models.IntegerField(default=5, verbose_name='آستانه موجودی کم')),
                ('about_us_text', models.TextField(blank=True, default='', verbose_name='متن درباره ما')),
                ('return_policy_text', models.TextField(blank=True, default='', verbose_name='متن سیاست مرجوعی')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین به\u200cروزرسانی')),
            ],
            options={
                'verbose_name': 'تنظیمات سایت',
                'verbose_name_plural': 'تنظیمات سایت',
            },
        ),
        migrations.CreateModel(
            name='ProductDraft',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='شناسه')),
                ('product_id', models.IntegerField(blank=True, null=True, verbose_name='شناسه محصول')),
                ('product_name', models.CharField(blank=True, default='', max_length=200, verbose_name='نام محصول')),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('ready', 'آماده انتشار'), ('published', 'منتشر شده'), ('rejected', 'رد شده')], default='draft', max_length=20, verbose_name='وضعیت')),
                ('has_real_photo', models.BooleanField(default=False, verbose_name='عکس اصلی واقعی دارد')),
                ('photo_count', models.IntegerField(default=0, verbose_name='تعداد عکس\u200cها')),
                ('has_origin_story', models.BooleanField(default=False, verbose_name='داستان مبدأ دارد')),
                ('origin_story_text', models.TextField(blank=True, default='', help_text='۲-۴ جمله واقعی از مبدأ محصول', verbose_name='متن داستان مبدأ')),
                ('has_final_price', models.BooleanField(default=False, verbose_name='قیمت نهایی دارد')),
                ('final_price', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='قیمت نهایی (تومان)')),
                ('has_policy_transparency', models.BooleanField(default=False, verbose_name='شفافیت سیاست\u200cها دارد')),
                ('has_real_contact', models.BooleanField(default=False, verbose_name='اطلاعات تماس واقعی دارد')),
                ('has_reviews_or_empty_state', models.BooleanField(default=False, verbose_name='نظرات یا حالت خالی دارد')),
                ('has_physical_presence', models.BooleanField(default=False, verbose_name='حضور فیزیکی دارد')),
                ('content_blocks', models.JSONField(blank=True, default=list, verbose_name='بلوک\u200cهای محتوا')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ انتشار')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین به\u200cروزرسانی')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_drafts', to=settings.AUTH_USER_MODEL, verbose_name='ایجادکننده')),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_drafts', to=settings.AUTH_USER_MODEL, verbose_name='منتشرکننده')),
            ],
            options={
                'verbose_name': 'پیش\u200cنویس محصول',
                'verbose_name_plural': 'پیش\u200cنویس\u200cهای محصول',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='SensitiveOperation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='شناسه')),
                ('operation_type', models.CharField(choices=[('delete_product', 'حذف محصول'), ('change_price', 'تغییر قیمت'), ('delete_user', 'حذف کاربر'), ('change_critical_settings', 'تغییر تنظیمات حیاتی'), ('publish_product', 'انتشار محصول')], max_length=30, verbose_name='نوع عملیات')),
                ('status', models.CharField(choices=[('pending', 'در انتظار تأیید'), ('approved', 'تأیید شده'), ('rejected', 'رد شده'), ('expired', 'منقضی شده')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('description', models.TextField(blank=True, default='', verbose_name='توضیحات')),
                ('entity_type', models.CharField(blank=True, default='', max_length=100, verbose_name='نوع موجودیت')),
                ('entity_id', models.CharField(blank=True, default='', max_length=100, verbose_name='شناسه موجودیت')),
                ('operation_data', models.JSONField(blank=True, null=True, verbose_name='داده\u200cهای عملیات')),
                ('requested_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ درخواست')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ تأیید')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ انقضا')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sensitive_operations_approved', to=settings.AUTH_USER_MODEL, verbose_name='تأییدکننده')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sensitive_operations_requested', to=settings.AUTH_USER_MODEL, verbose_name='درخواست\u200cدهنده')),
            ],
            options={
                'verbose_name': 'عملیات حساس',
                'verbose_name_plural': 'عملیات\u200cهای حساس',
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='شناسه')),
                ('action', models.CharField(choices=[('login', 'ورود'), ('logout', 'خروج'), ('create', 'ایجاد'), ('update', 'ویرایش'), ('delete', 'حذف'), ('publish', 'انتشار'), ('approve', 'تأیید'), ('reject', 'رد'), ('add_member', 'افزودن عضو'), ('remove_member', 'حذف عضو'), ('admin_deactivate', 'غیرفعال\u200cسازی ادمین'), ('admin_activate', 'فعال\u200cسازی ادمین'), ('change_settings', 'تغییر تنظیمات'), ('order_approve', 'تأیید سفارش'), ('order_reject', 'رد سفارش'), ('review_approve', 'تأیید نظر'), ('review_reject', 'رد نظر'), ('review_reply', 'پاسخ به نظر')], max_length=30, verbose_name='نوع فعالیت')),
                ('description', models.TextField(blank=True, default='', verbose_name='توضیحات')),
                ('entity_type', models.CharField(blank=True, default='', help_text='مثال: product, order, review, user', max_length=100, verbose_name='نوع موجودیت')),
                ('entity_id', models.CharField(blank=True, default='', max_length=100, verbose_name='شناسه موجودیت')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='آی\u200cپی')),
                ('user_agent', models.TextField(blank=True, default='', verbose_name='User Agent')),
                ('changes', models.JSONField(blank=True, help_text='تغییرات اعمال شده به صورت JSON', null=True, verbose_name='تغییرات')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='تاریخ')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'لاگ فعالیت',
                'verbose_name_plural': 'لاگ\u200cهای فعالیت',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='family_pane_user_id_f6265c_idx'), models.Index(fields=['action', 'created_at'], name='family_pane_action_d1c86f_idx'), models.Index(fields=['entity_type', 'entity_id'], name='family_pane_entity__93fe6d_idx')],
            },
        ),
    ]
