# Generated by Django 5.2.17 on 2026-08-21 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_add_user_to_supplier'),
        ('family_panel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blocks', models.JSONField(default=list, help_text='لیست بلوک\u200cهای محتوا به صورت JSON')),
                ('is_published', models.BooleanField(default=False, help_text='آیا محتوا منتشر شده است؟')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, help_text='زمان آخرین انتشار', null=True)),
                ('draft_title', models.CharField(blank=True, help_text='عنوان پیش\u200cنویس', max_length=200)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='content_blocks', to='catalog.product')),
            ],
            options={
                'verbose_name': 'محتوای محصول',
                'verbose_name_plural': 'محتواهای محصولات',
            },
        ),
    ]
