# Generated by Django 5.2.17 on 2026-08-24 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaqItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=250, verbose_name='سوال')),
                ('answer', models.TextField(help_text='می\u200cتواند چند خط باشد؛ هر Enter یک خط جدید نمایش داده می\u200cشود.', verbose_name='پاسخ')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال (نمایش در سایت)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد')),
            ],
            options={
                'verbose_name': 'سوال متداول',
                'verbose_name_plural': '❓ سوالات متداول',
                'ordering': ('sort_order', 'id'),
            },
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_body',
            field=models.TextField(default='ریهان یک فروشگاه آنلاین اعتمادمحور است.\n\nتیم ریهان سال\u200cهاست تجربه خرید و ارزیابی دقیق کالاها را برای اطرافیان داشته است؛ از اقلام روزمره تا محصولات خاص - هر محصولی که ارزش و کیفیت داشته باشد.\n\nحالا این تجربه را در قالب یک وب\u200cسایت حرفه\u200cای ارائه می\u200cدهیم؛ بدون برندسازی شخصی، لوکس، باوقار، تدریجی و خانوادگی.\n\n> محصول متغیر است؛ اعتماد ثابت.\n\n# اصول دهگانه ما\n\n۱. داستان\u200cمحور: هر محصول داستانی دارد\n۲. اعتماد ثابت، محصول متغیر: برند به محصول گره نمی\u200cخورد\n۳. انعطاف کامل: آماده تغییر بر اساس نیاز مشتری\n۴. شأن و شخصیت: احترام به مشتری در همه مراحل\n۵. خانوادگی: کسب\u200cوکار خانوادگی با رشد تدریجی\n۶. تدریجی: رشد ۵ ساله بدون عجله\n۷. مستند و سیستمی: همه چیز ثبت و قابل پیگیری\n۸. محدودیت\u200cها محترم: پذیرش واقعیت\u200cها و کار با آن\u200cها\n۹. مستقل از خارج: عدم وابستگی به پلتفرم\u200cهای خارجی\n۱۰. کنترل کامل ادمین: مدیریت همه جنبه\u200cها از پنل', help_text='قواعد نوشتن: خط خالی = پاراگراف جدید | خطی که با «#» شروع شود = تیتر بخش | خطوطی که با «-» شروع شوند = فهرست نقطه\u200cای | خطوطی که با «۱.» «۲.» شروع شوند = فهرست شماره\u200cای | خطی که با «>» شروع شود = نقل\u200cقول برجسته', verbose_name='متن صفحه درباره ما'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_title',
            field=models.CharField(default='درباره ریهان', max_length=120, verbose_name='عنوان صفحه درباره ما'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='faq_intro',
            field=models.TextField(blank=True, default='', help_text='اگر خالی بماند هیچ متنی بالای سوالات نمایش داده نمی\u200cشود. خودِ سوال\u200cها از بخش «سوالات متداول» پنل مدیریت شده\u200cاند.', verbose_name='متن بالای سوالات متداول'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='return_policy_body',
            field=models.TextField(default='ما در ریهان به کیفیت محصولات خود اطمینان داریم؛ اگر به هر دلیلی از خرید خود راضی نبودید، تا ۷ روز فرصت مرجوعی دارید.\n\n# شرایط مرجوعی\n\n- محصول باید در بسته\u200cبندی اصلی و استفاده نشده باشد\n- برچسب\u200cها و اتیکت\u200cها نباید کنده شده باشند\n- محصول نباید آسیب دیده یا لکه\u200cدار شده باشد\n- فقط تا ۷ روز پس از تحویل قابل مرجوع است\n\n# فرآیند مرجوعی\n\n۱. با پشتیبانی تماس بگیرید\n۲. شماره سفارش و دلیل مرجوعی را اعلام کنید\n۳. هماهنگی برای ارسال محصول انجام می\u200cشود\n۴. پس از دریافت و تأیید سلامت محصول، مبلغ به حساب شما بازگردانده می\u200cشود\n۵. بازگشت وجه طی ۳ تا ۵ روز کاری انجام می\u200cشود\n\n# هزینه\u200cها\n\nنکته مهم: هزینه ارسال مرجوعی بر عهده مشتری است؛ مگر اینکه محصول آسیب\u200cدیده یا اشتباه ارسال شده باشد.\n\n# استثنائات\n\nموارد زیر قابل مرجوع نیستند:\n\n- محصولات بهداشتی و شخصی (به دلایل بهداشتی)\n- محصولات سفارشی\u200cسازی شده\n- محصولاتی که بیش از ۷ روز از تحویل آن\u200cها گذشته باشد', help_text='قواعد نوشتن: خط خالی = پاراگراف جدید | خطی که با «#» شروع شود = تیتر بخش | خطوطی که با «-» شروع شوند = فهرست نقطه\u200cای | خطوطی که با «۱.» «۲.» شروع شوند = فهرست شماره\u200cای | خطی که با «>» شروع شود = نقل\u200cقول برجسته', verbose_name='متن کامل سیاست مرجوعی'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='return_policy_title',
            field=models.CharField(default='سیاست مرجوعی', max_length=120, verbose_name='عنوان صفحه سیاست مرجوعی'),
        ),
    ]
