# Generated by Django 5.2.17 on 2026-08-25 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_seed_default_faqs'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='buy_commitments',
            field=models.TextField(default='۷ روز ضمانت بازگشت وجه\nارسال ایمن و بیمه\u200cشده\nتضمین سلامت و اصالت کالا', help_text='هر خط یک تعهد. در صفحه محصول زیر دکمه خرید نمایش داده می\u200cشود. اگر خالی باشد هیچ تعهدی نشان داده نمی\u200cشود.', verbose_name='تعهدهای زیر دکمه خرید'),
        ),
    ]
