# Generated by Django 5.2.17 on 2026-08-25 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_sitesettings_buy_commitments'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='sms_notify_customers',
            field=models.BooleanField(default=True, help_text='پس از ثبت کد رهگیری، مشتری لینک پیگیری یک\u200cکلیکی دریافت کند', verbose_name='پیامک کد رهگیری به مشتری'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='sms_notify_suppliers',
            field=models.BooleanField(default=True, help_text='با ثبت سفارشِ محصولِ تامین\u200cکننده\u200cدار، پیامک خودکار دریافت کند', verbose_name='پیامک سفارش جدید به تامین\u200cکننده'),
        ),
    ]
