# Generated by Django 5.2.17 on 2026-08-25 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_sitesettings_sms_notify_customers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='brand_name_latin',
            field=models.CharField(default='Rihan', help_text='در همه پیامک\u200cها، متن دستور ارسال و تصویر استوری با همین املای لاتین نمایش داده می\u200cشود', max_length=40, verbose_name='نام برند (لاتین، برای پیامک و استوری)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='share_hashtags',
            field=models.CharField(blank=True, default='#Rihan #فروشگاه_آنلاین #خرید_آنلاین', help_text='با فاصله جدا شود؛ در کپشن استوری و پیام اشتراک\u200cگذاری می\u200cآید', max_length=300, verbose_name='هشتگ\u200cهای اشتراک\u200cگذاری'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='share_message_text',
            field=models.TextField(blank=True, default='', help_text='اول پیام هنگام ارسال محصول در پیام\u200cرسان\u200cها؛ بعد از آن نام محصول، لینک کوتاه و هشتگ\u200cها خودکار می\u200cآید', verbose_name='متن پیام اشتراک\u200cگذاری محصول'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='sms_text_customer_shipped',
            field=models.TextField(blank=True, default='', help_text='متغیرها: {order_number} {carrier} {tracking_code} {link} {brand} — خالی = قالب پیش\u200cفرض', verbose_name='قالب پیامک رهگیری به مشتری'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='sms_text_supplier_assign',
            field=models.TextField(blank=True, default='', help_text='متغیرها: {order_number} {items} {link} {brand} — خالی = قالب پیش\u200cفرض', verbose_name='قالب پیامک سفارش جدید به تامین\u200cکننده'),
        ),
    ]
