# Generated by Django 5.2.17 on 2026-08-25 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_sitesettings_brand_name_latin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='trust_badges',
            field=models.TextField(default='پرداخت امن | کارت\u200cبه\u200cکارت با تأیید سفارش\nگارانتی مرجوعی | ۷ روز بدون قید و شرط\nارسال مطمئن | بسته\u200cبندی ایمن و بیمه\u200cشده\nپشتیبانی تلفنی | پاسخگویی و همراهی تا تحویل', help_text='هر خط یک نشان با قالب «عنوان | زیرنویس» — در صفحه محصول بالای توضیحات نمایش داده می\u200cشود. آیکون\u200cها به ترتیب ثابت هستند.', verbose_name='نشان\u200cهای اعتماد صفحه محصول'),
        ),
    ]
