# Generated by Django 5.2.17 on 2026-08-29 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_sitesettings_privacy_body_sitesettings_privacy_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='supplier_deadline_hours',
            field=models.PositiveSmallIntegerField(default=48, help_text='اگر تامین\u200cکننده ظرف این ساعت\u200cها کد رهگیری ثبت نکند، مرسوله «دیرکرد» می\u200cخورد: در داشبورد ادمین قرمز می\u200cشود و یادآوری پیامکی خودکار اجرا می\u200cشود.', verbose_name='مهلت ارسال تامین\u200cکننده (ساعت)'),
        ),
    ]
