# Generated by Django 5.2.17 on 2026-09-01 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_sitesettings_supplier_deadline_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='wa_fab_enabled',
            field=models.BooleanField(default=True, help_text='با روشن بودن، دکمهٔ شناور واتساپ با کد اتصال در صفحهٔ سبد و تسویه نمایش داده می\u200cشود.', verbose_name='دکمهٔ «پاسخ سریع در واتساپ»'),
        ),
    ]
