# Generated by Django 5.2.17 on 2026-09-01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_sitesettings_wa_fab_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='price_note_enabled',
            field=models.BooleanField(default=True, help_text='با روشن بودن، «پیام کنار قیمت» روی کارت محصول در صفحه اصلی و زیر قیمت در صفحه محصول نمایش داده می‌شود.', verbose_name='فعال‌سازی پیام کنار قیمت'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='price_note_text',
            field=models.TextField(blank=True, default='', help_text='کوتاه و توجیه‌کنندهٔ قیمت بنویسید؛ مثال: «برداشت دستی از دامنه‌های وحشی هوراند؛ بدون هیچ افزودنی — به همین قیمت نیست.» اگر خالی بماند هیچ‌چیز نمایش داده نمی‌شود، حتی با فعال بودن کلید.', verbose_name='متن پیام کنار قیمت'),
        ),
    ]
