# Generated by Django 5.2.17 on 2026-08-17 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_category_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorytransaction',
            name='reference_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Reference ID'),
        ),
    ]
