# Generated by Django 5.2.17 on 2026-08-23 08:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_add_user_to_supplier'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'دسته\u200cبندی', 'verbose_name_plural': 'دسته\u200cبندی\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='contentblock',
            options={'ordering': ['sort_order'], 'verbose_name': 'بلوک محتوای صفحه', 'verbose_name_plural': 'بلوک\u200cهای محتوای صفحات'},
        ),
        migrations.AlterModelOptions(
            name='inventory',
            options={'verbose_name': 'موجودی انبار', 'verbose_name_plural': 'موجودی انبار'},
        ),
        migrations.AlterModelOptions(
            name='inventorytransaction',
            options={'ordering': ['-created_at'], 'verbose_name': 'تراکنش موجودی', 'verbose_name_plural': 'تاریخچه موجودی انبار'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-is_featured', '-created_at'], 'verbose_name': 'محصول', 'verbose_name_plural': 'محصولات'},
        ),
        migrations.AlterModelOptions(
            name='supplier',
            options={'verbose_name': 'تامین\u200cکننده', 'verbose_name_plural': 'تامین\u200cکنندگان'},
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='products/%Y/%m/', verbose_name='فایل تصویر')),
                ('caption', models.CharField(blank=True, max_length=255, verbose_name='متن جایگزین (Alt)')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='catalog.product')),
            ],
            options={
                'verbose_name': 'عکس محصول',
                'verbose_name_plural': 'گالری تصاویر محصولات',
                'ordering': ['sort_order', 'created_at'],
            },
        ),
    ]
