# Generated by Django 5.2.17 on 2026-08-23 10:28

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_category_options_alter_contentblock_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=150, verbose_name='نام دسته'),
        ),
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='catalog.category', verbose_name='دسته والد'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(allow_unicode=True, max_length=180, unique=True, verbose_name='نامک (آدرس)'),
        ),
        migrations.AlterField(
            model_name='contentblock',
            name='block_type',
            field=models.CharField(choices=[('text', 'Text'), ('heading', 'Heading'), ('image', 'Image'), ('gallery', 'Gallery'), ('video', 'Video'), ('link', 'Link'), ('quote', 'Quote'), ('table', 'Table'), ('spacer', 'Spacer'), ('cta', 'Call to Action'), ('trust_badges', 'Trust Badges'), ('related_products', 'Related Products')], max_length=50, verbose_name='نوع بلوک'),
        ),
        migrations.AlterField(
            model_name='contentblock',
            name='content',
            field=models.JSONField(blank=True, default=dict, verbose_name='محتوای بلوک'),
        ),
        migrations.AlterField(
            model_name='contentblock',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال'),
        ),
        migrations.AlterField(
            model_name='contentblock',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='unit',
            field=models.CharField(blank=True, max_length=20, verbose_name='واحد'),
        ),
        migrations.AlterField(
            model_name='product',
            name='base_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='قیمت پایه (تومان)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.category', verbose_name='دسته\u200cبندی'),
        ),
        migrations.AlterField(
            model_name='product',
            name='final_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='قیمت نهایی (خودکار محاسبه می\u200cشود)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='images',
            field=models.JSONField(blank=True, default=list, verbose_name='تصاویر (مدیریت از بخش گالری)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='نمایش در صفحه اصلی'),
        ),
        migrations.AlterField(
            model_name='product',
            name='long_description',
            field=models.TextField(blank=True, verbose_name='توضیحات کامل'),
        ),
        migrations.AlterField(
            model_name='product',
            name='margin_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='حاشیه سود (درصد)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, verbose_name='متادیتا (فنی)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=150, verbose_name='نام محصول'),
        ),
        migrations.AlterField(
            model_name='product',
            name='origin_story',
            field=models.TextField(verbose_name='داستان محصول'),
        ),
        migrations.AlterField(
            model_name='product',
            name='seo_description',
            field=models.CharField(blank=True, max_length=160, null=True, verbose_name='توضیح سئو'),
        ),
        migrations.AlterField(
            model_name='product',
            name='seo_keywords',
            field=models.JSONField(blank=True, null=True, verbose_name='کلمات کلیدی سئو'),
        ),
        migrations.AlterField(
            model_name='product',
            name='seo_title',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='عنوان سئو'),
        ),
        migrations.AlterField(
            model_name='product',
            name='shipping_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='هزینه ارسال (تومان)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='short_description',
            field=models.TextField(verbose_name='توضیح کوتاه (نمایش در لیست)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(allow_unicode=True, max_length=100, unique=True, verbose_name='نامک (آدرس صفحه)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('active', 'فعال (منتشر شده)'), ('inactive', 'غیرفعال (مخفی)'), ('out_of_stock', 'ناموجود')], default='draft', max_length=20, verbose_name='وضعیت انتشار'),
        ),
        migrations.AlterField(
            model_name='product',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='catalog.supplier', verbose_name='تامین\u200cکننده'),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(blank=True, max_length=20, verbose_name='واحد فروش (مثلا کیلوگرم)'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='city',
            field=models.CharField(max_length=100, verbose_name='شهر'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='phone',
            field=models.CharField(blank=True, max_length=11, verbose_name='تلفن همراه'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='title',
            field=models.CharField(max_length=150, verbose_name='عنوان / نام تامین\u200cکننده'),
        ),
    ]
