# Generated by Django 5.2.17 on 2026-08-23 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_category_is_active_alter_category_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='عنوان گزینه (مثلاً بسته ۵۰۰ گرمی یا L / آبی)')),
                ('color_name', models.CharField(blank=True, default='', max_length=50, verbose_name='نام رنگ (اختیاری)')),
                ('color_hex', models.CharField(blank=True, default='', max_length=9, verbose_name='کد رنگ (اختیاری، مثل #AA2233)')),
                ('price', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='قیمت این گزینه (تومان)')),
                ('unit', models.CharField(default='بسته', max_length=30, verbose_name='واحد نمایش')),
                ('stock_quantity', models.PositiveIntegerField(default=0, verbose_name='موجودی')),
                ('reserved_quantity', models.PositiveIntegerField(default=0, editable=False, verbose_name='رزرو شده')),
                ('low_stock_threshold', models.PositiveIntegerField(default=5, verbose_name='آستانه هشدار کمبود')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='catalog.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'واریانت محصول',
                'verbose_name_plural': 'واریانت\u200cهای محصولات',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
