# Generated by Django 5.2.17 on 2026-08-25 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_productvariant'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='compare_at_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='اگر بزرگ\u200cتر از قیمت فعلی باشد، به\u200cصورت خط\u200cخورده + درصد تخفیف نمایش داده می\u200cشود.', max_digits=10, null=True, verbose_name='قیمت قبل از تخفیف (خط\u200cخورده)'),
        ),
        migrations.AddField(
            model_name='product',
            name='curation_story',
            field=models.TextField(blank=True, default='', help_text='قواعد متن: خط خالی=پاراگراف، #=تیتر، -=فهرست، ۱.=شماره\u200cای، >=نقل\u200cقول. چطور ده\u200cها نمونه تست شد و چرا این انتخاب شد؟', verbose_name='داستان گزینش و آزمون کیفیت'),
        ),
        migrations.AddField(
            model_name='product',
            name='deep_dive',
            field=models.TextField(blank=True, default='', help_text='متن ساختاریافته انتهای صفحه برای گوگل و هوش\u200cهای مصنوعی. همان قواعد متن بالا.', verbose_name='مقاله جامع سئو (Deep-Dive)'),
        ),
        migrations.AddField(
            model_name='product',
            name='fit_for',
            field=models.TextField(blank=True, default='', help_text='هر خط یک مورد؛ خط\u200cها با «-» شروع شوند فهرست می\u200cشوند. خالی = بخش مخفی.', verbose_name='این کالا برای شماست اگر...'),
        ),
        migrations.AddField(
            model_name='product',
            name='not_fit_for',
            field=models.TextField(blank=True, default='', help_text='هر خط یک مورد؛ صادقانه بنویسید چه کسانی این کالا برایشان مناسب نیست.', verbose_name='لطفاً سفارش ندهید اگر...'),
        ),
        migrations.AddField(
            model_name='product',
            name='result_headline',
            field=models.CharField(blank=True, default='', help_text='مثلاً: «دیگر نگران تقلبی بودن سماق نباشید» — اگر خالی باشد نمایش داده نمی\u200cشود.', max_length=180, verbose_name='تیتر نتیجه\u200cمحور (بالای نام محصول)'),
        ),
        migrations.AddField(
            model_name='product',
            name='share_count',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='تعداد اشتراک\u200cگذاری'),
        ),
        migrations.CreateModel(
            name='ProductFaq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=250, verbose_name='سوال')),
                ('answer', models.TextField(verbose_name='پاسخ')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='catalog.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'سوال متداول محصول',
                'verbose_name_plural': 'سوالات متداول محصولات',
                'ordering': ('sort_order', 'id'),
            },
        ),
    ]
