# Generated by Django 5.2.17 on 2026-08-25 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_product_compare_at_price_product_curation_story_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShortLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=12, unique=True, verbose_name='کد')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='short_links', to='catalog.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'لینک کوتاه',
                'verbose_name_plural': 'لینک\u200cهای کوتاه',
            },
        ),
    ]
