# Generated by Django 5.2.17 on 2026-08-26 02:11

import src.core.upload_validation
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_shortlink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='products/%Y/%m/', validators=[src.core.upload_validation.validate_upload_image], verbose_name='فایل تصویر'),
        ),
    ]
