# Generated by Django 5.2.17 on 2026-08-28 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_alter_productimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='cost_price',
            field=models.DecimalField(decimal_places=0, default=0, help_text='بهای تمام\u200cشده این واریانت — مبنای محاسبه حاشیه سود و تسویه تامین\u200cکننده (D-113)', max_digits=12, verbose_name='قیمت خرید از تامین\u200cکننده (تومان)'),
        ),
    ]
