# Generated by Django 5.2.17 on 2026-08-28 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_productvariant_cost_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='is_default',
            field=models.BooleanField(default=False, help_text='قیمت همین گزینه به\u200cعنوان قیمت اصلی محصول در لیست/صفحه اصلی نمایش داده می\u200cشود — فقط یکی از گزینه\u200cها', verbose_name='گزینه استاندارد (نمایش در صفحه اصلی و لیست)'),
        ),
    ]
