# Generated by Django 5.2.17 on 2026-08-29 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_productvariant_is_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='geo_answer',
            field=models.TextField(blank=True, default='', help_text='کادر «پاسخ سریع» بالای صفحه محصول — ۲ تا ۳ جملهٔ پر از فکت (خاستگاه، بافت، بدون افزودنی، ضمانت). همان متنی که هوش\u200cهای مصنوعی به\u200cعنوان پاسخ مستقیم نقل می\u200cکنند (D-118).', verbose_name='پاسخ سریع (GEO)'),
        ),
    ]
