# Generated by Django 5.2.17 on 2026-09-02 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_product_geo_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='share_text',
            field=models.TextField(blank=True, default='', help_text='خالی = متن عمومی از تنظیمات سایت. جای\u200cنگه\u200cدار {min_price} = ارزان\u200cترین بسته. بعد از این متن، نام محصول، لینک کوتاه و هشتگ\u200cها خودکار اضافه می\u200cشود.', verbose_name='متن اختصاصی اشتراک\u200cگذاری'),
        ),
    ]
