# Generated by Django 5.2.17 on 2026-08-23 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='ریهان', help_text='این نام در لوگوی هدر و پنل مدیریت نمایش داده می\u200cشود.', max_length=100, verbose_name='نام فروشگاه')),
                ('hero_badge', models.CharField(default='فروشگاه آنلاین اعتمادمحور', max_length=120, verbose_name='برچسب بالای عنوان')),
                ('hero_title', models.TextField(default='انتخاب مطمئن،\nهر محصولی که باشد', help_text='هر خط با کلید Enter جدا می\u200cشود و در دو سطر نمایش داده می\u200cشود.', verbose_name='عنوان اصلی صفحه اول')),
                ('hero_subtitle', models.TextField(default='ریهان یک فروشگاه عمومی با تعداد زیاد کالا نیست.\nارزش ریهان در انتخاب\u200cهای دقیق و معنادار است.', verbose_name='توضیح زیر عنوان')),
                ('hero_quote', models.TextField(blank=True, default='', help_text='اگر خالی بماند این بخش نمایش داده نمی\u200cشود.', verbose_name='پیام ویژه / نقل\u200cقول')),
                ('featured_title', models.CharField(default='محصولات برگزیده', max_length=120, verbose_name='عنوان بخش محصولات')),
                ('announcement_active', models.BooleanField(default=False, verbose_name='نمایش نوار اطلاعیه بالای سایت')),
                ('announcement_text', models.CharField(blank=True, default='', help_text='مثال: ارسال رایگان برای خریدهای بالای ۵۰۰ هزار تومان', max_length=250, verbose_name='متن اطلاعیه')),
                ('contact_phone', models.CharField(blank=True, default='', max_length=30, verbose_name='تلفن تماس')),
                ('contact_email', models.EmailField(blank=True, default='', max_length=254, verbose_name='ایمیل')),
                ('contact_address', models.TextField(blank=True, default='فروشگاه آنلاین — ارسال به سراسر ایران', verbose_name='آدرس / توضیح تماس')),
                ('contact_hours', models.CharField(default='هر روز ۱۱ تا ۱۹', max_length=120, verbose_name='ساعات پاسخگویی')),
                ('instagram_url', models.URLField(blank=True, default='', verbose_name='آدرس اینستاگرام')),
                ('telegram_url', models.URLField(blank=True, default='', verbose_name='آدرس تلگرام')),
                ('whatsapp_number', models.CharField(blank=True, default='', help_text='فقط شماره با کد کشور، مثال: 989123456789', max_length=30, verbose_name='شماره واتساپ')),
                ('footer_tagline', models.CharField(default='انتخاب مطمئن، هر محصولی که باشد', max_length=200, verbose_name='شعار زیر نام برند در فوتر')),
                ('footer_description', models.TextField(default='فروشگاه آنلاین اعتمادمحور با محصولات اصیل و با کیفیت', verbose_name='توضیح کوتاه فوتر')),
                ('footer_copyright', models.CharField(default='© ۱۴۰۵ ریهان. تمام حقوق محفوظ است.', max_length=200, verbose_name='متن کپی\u200cرایت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین به\u200cروزرسانی')),
            ],
            options={
                'verbose_name': '⚙️ تنظیمات سایت',
                'verbose_name_plural': '⚙️ تنظیمات سایت',
            },
        ),
    ]
