# Generated by Django 5.0.14 on 2026-08-14 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15, verbose_name='شماره موبایل')),
                ('otp_code', models.CharField(max_length=6, verbose_name='کد یکبارمصرف (۶ رقم)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('expires_at', models.DateTimeField(verbose_name='زمان انقضا')),
                ('is_used', models.BooleanField(default=False, verbose_name='استفاده\u200cشده')),
                ('attempts', models.PositiveIntegerField(default=0, verbose_name='تعداد تلاش\u200cها')),
            ],
            options={
                'verbose_name': 'کد یکبارمصرف (OTP)',
                'verbose_name_plural': 'کدهای یکبارمصرف',
                'ordering': ['-created_at'],
            },
        ),
    ]
