# Generated by Django 5.2.17 on 2026-08-23 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='core_auditl_entity__244637_idx',
            old_name='core_auditl_entity_idx',
        ),
        migrations.RenameIndex(
            model_name='featureflag',
            new_name='core_featur_is_enab_411c01_idx',
            old_name='core_featur_is_enab_idx',
        ),
    ]
