# Generated by Django 5.2.17 on 2026-08-23 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rihan_auth', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='devicetoken',
            new_name='rihan_auth__user_id_97d08e_idx',
            old_name='auth_device_user_i_idx',
        ),
        migrations.RenameIndex(
            model_name='loginattempt',
            new_name='rihan_auth__phone_66484f_idx',
            old_name='auth_login_phone_c_idx',
        ),
        migrations.RenameIndex(
            model_name='loginattempt',
            new_name='rihan_auth__ip_addr_0c6ab5_idx',
            old_name='auth_login_ip_c_idx',
        ),
        migrations.RenameIndex(
            model_name='phoneotp',
            new_name='rihan_auth__phone_17e046_idx',
            old_name='auth_phoneo_phone_c_idx',
        ),
    ]
