# Generated by Django 5.2.17 on 2026-08-23 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rihan_auth', '0002_rename_auth_device_user_i_idx_rihan_auth__user_id_97d08e_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginattempt',
            name='action',
            field=models.CharField(choices=[('otp_request', 'درخواست OTP'), ('otp_verify_success', 'تأیید موفق OTP'), ('otp_verify_failed', 'تأیید ناموفق OTP'), ('device_login', 'ورود با DeviceToken'), ('password_login', 'ورود با رمز پشتیبان'), ('password_failed', 'رمز عبور نادرست (D-095)'), ('password_reset', 'تنظیم/بازنشانی رمز عبور'), ('logout', 'خروج'), ('lockout', 'قفل موقت')], max_length=50, verbose_name='نوع عملیات'),
        ),
    ]
