# Generated by Django 5.2.17 on 2026-08-24 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rihan_auth', '0003_alter_loginattempt_action'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp_enabled', models.BooleanField(default=True, verbose_name='ورود و ثبت\u200cنام با کد پیامکی')),
                ('password_enabled', models.BooleanField(default=True, verbose_name='ورود با رمز عبور')),
                ('default_method', models.CharField(choices=[('otp', 'کد یکبارمصرف (پیامک)'), ('password', 'رمز عبور')], default='otp', max_length=10, verbose_name='روش پیش\u200cفرض (تب اول صفحه ورود)')),
                ('otp_ttl_minutes', models.PositiveSmallIntegerField(default=5, verbose_name='مهلت اعتبار کد (دقیقه)')),
                ('otp_max_attempts', models.PositiveSmallIntegerField(default=3, verbose_name='حداکثر تلاش مجاز برای هر کد')),
                ('show_code_on_sms_fail', models.BooleanField(default=True, help_text='حالت اضطراری/تست: اگر هیچ سرویس پیامکی در دسترس نباشد، کد روی صفحه نمایش داده می\u200cشود تا مسیر مشتری قطع نشود. در بهره\u200cبرداری واقعی خاموش کنید.', verbose_name='نمایش کد در صفحه وقتی پیامک ارسال نمی\u200cشود')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین تغییر')),
            ],
            options={
                'verbose_name': '🔐 تنظیمات ورود و پیامک',
                'verbose_name_plural': '🔐 تنظیمات ورود و پیامک',
            },
        ),
        migrations.CreateModel(
            name='SmsProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='مثلاً: «کاوه\u200cنگار اصلی» یا «کاوه\u200cنگار پشتیبان»', max_length=100, verbose_name='عنوان (برای تشخیص)')),
                ('provider_type', models.CharField(choices=[('kavenegar', 'کاوه\u200cنگار'), ('ghasedak', 'قاصدک'), ('sms_ir', 'اس\u200cام\u200cاس آی\u200cآر'), ('farazsms', 'فراز اس\u200cام\u200cاس')], default='kavenegar', max_length=20, verbose_name='نوع سرویس')),
                ('api_key', models.CharField(help_text='از پنل سرویس\u200cدهنده دریافت می\u200cشود (کاوه\u200cنگار: تنظیمات → کلید API)', max_length=255, verbose_name='کلید API')),
                ('otp_template', models.CharField(blank=True, default='rihan-otp', help_text='نام قالبی که در پنل سرویس\u200cدهنده ساخته\u200cاید و متغیر %token دارد', max_length=100, verbose_name='نام قالب تأییدیه')),
                ('sender', models.CharField(blank=True, default='', max_length=20, verbose_name='شماره فرستنده (اختیاری)')),
                ('is_active', models.BooleanField(default=False, help_text='فقط یک سرویس می\u200cتواند فعال باشد؛ با فعال\u200cکردن این، بقیه خودکار غیرفعال می\u200cشوند.', verbose_name='فعال (سرویس در حال استفاده)')),
                ('priority', models.PositiveIntegerField(default=100, help_text='وقتی سرویس فعال قطع شود، بقیه به همین ترتیب امتحان می\u200cشوند.', verbose_name='اولویت جایگزین (عدد کوچک\u200cتر = زودتر)')),
                ('last_status', models.CharField(blank=True, default='', editable=False, max_length=255, verbose_name='آخرین وضعیت ارسال')),
                ('last_used_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='آخرین استفاده')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین تغییر')),
            ],
            options={
                'verbose_name': '📡 سرویس\u200cدهنده پیامک',
                'verbose_name_plural': '📡 سرویس\u200cدهنده\u200cهای پیامک',
                'ordering': ('-is_active', 'priority', 'id'),
            },
        ),
        migrations.AddField(
            model_name='phoneotp',
            name='sent_via',
            field=models.CharField(blank=True, default='', help_text='نام سرویس\u200cدهنده پیامکی که این کد را ارسال کرده (D-103)', max_length=100, verbose_name='ارسال\u200cشده از طریق'),
        ),
    ]
