# Generated by Django 5.2.17 on 2026-08-26 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rihan_auth', '0004_authsettings_smsprovider_phoneotp_sent_via'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminLoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('ip', models.GenericIPAddressField(blank=True, db_index=True, null=True)),
                ('succeeded', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'تلاش ورود ادمین',
                'verbose_name_plural': 'تلاش\u200cهای ورود ادمین',
            },
        ),
    ]
