# Generated by Django 5.0.14 on 2026-08-14 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(editable=False, max_length=50, unique=True, verbose_name='شماره سفارش')),
                ('customer_name', models.CharField(max_length=150, verbose_name='نام و نام خانوادگی')),
                ('customer_phone', models.CharField(max_length=20, verbose_name='شماره موبایل')),
                ('customer_email', models.EmailField(blank=True, max_length=254, verbose_name='ایمیل (اختیاری)')),
                ('province', models.CharField(max_length=100, verbose_name='استان')),
                ('city', models.CharField(max_length=100, verbose_name='شهر')),
                ('shipping_address', models.TextField(verbose_name='نشانی دقیق پستی')),
                ('postal_code', models.CharField(max_length=20, verbose_name='کد پستی')),
                ('customer_notes', models.TextField(blank=True, verbose_name='یادداشت سفارش')),
                ('items_total', models.PositiveBigIntegerField(default=0, verbose_name='جمع اقلام (تومان)')),
                ('shipping_cost', models.PositiveBigIntegerField(default=0, verbose_name='هزینه ارسال (D-046: لحاظ در قیمت کالا)')),
                ('grand_total', models.PositiveBigIntegerField(default=0, verbose_name='مبلغ نهایی (تومان)')),
                ('status', models.CharField(choices=[('pending_payment', 'در انتظار پرداخت'), ('payment_submitted', 'رسید ثبت\u200cشده / در حال بررسی'), ('confirmed', 'تأییدشده و آماده\u200cسازی'), ('shipped', 'ارسال\u200cشده به مقصد'), ('delivered', 'تحویل داده\u200cشده'), ('cancelled', 'لغوشده')], default='pending_payment', max_length=30, verbose_name='وضعیت سفارش')),
                ('payment_method', models.CharField(choices=[('card_to_card', 'کارت\u200cبه\u200cکارت'), ('online_gateway', 'درگاه پرداخت آنلاین')], default='card_to_card', max_length=30, verbose_name='روش پرداخت')),
                ('tracking_code', models.CharField(blank=True, max_length=100, verbose_name='کد رهگیری پستی / باربری')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین تغییر')),
            ],
            options={
                'verbose_name': 'سفارش',
                'verbose_name_plural': 'سفارش\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_title', models.CharField(max_length=255, verbose_name='عنوان محصول')),
                ('product_sku', models.CharField(max_length=50, verbose_name='کد کالا')),
                ('unit_price', models.PositiveBigIntegerField(verbose_name='قیمت واحد (تومان)')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='تعداد')),
                ('subtotal', models.PositiveBigIntegerField(verbose_name='جمع ردیف (تومان)')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='سفارش')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='catalog.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'آیتم سفارش',
                'verbose_name_plural': 'آیتم\u200cهای سفارش',
            },
        ),
    ]
