# Generated by Django 5.0.14 on 2026-08-14 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderFinance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gross_revenue', models.PositiveBigIntegerField(default=0, verbose_name='درآمد ناخالص (تومان)')),
                ('total_supply_cost', models.PositiveBigIntegerField(default=0, verbose_name='مجموع هزینه تأمین کالا (تومان)')),
                ('actual_shipping_cost', models.PositiveBigIntegerField(default=45000, verbose_name='هزینه واقعی ارسال پستی (تومان)')),
                ('net_profit', models.BigIntegerField(default=0, verbose_name='سود ناخالص واقعی (تومان)')),
                ('margin_percent', models.FloatField(default=0.0, verbose_name='حاشیه سود واقعی (درصد)')),
                ('supplier_paid', models.BooleanField(default=False, verbose_name='تسویه با تأمین\u200cکننده')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='finance', to='orders.order', verbose_name='سفارش')),
            ],
            options={
                'verbose_name': 'حساب و کتاب مالی سفارش (M6)',
                'verbose_name_plural': 'حساب و کتاب مالی سفارش\u200cها',
                'ordering': ['-order__created_at'],
            },
        ),
    ]
