# Generated by Django 5.0.14 on 2026-08-14 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='نام دسته\u200cبندی')),
                ('slug', models.SlugField(allow_unicode=True, max_length=180, unique=True, verbose_name='اسلاگ')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='آیکون')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی',
                'verbose_name_plural': 'دسته\u200cبندی\u200cها',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان محصول')),
                ('slug', models.SlugField(allow_unicode=True, max_length=280, unique=True, verbose_name='اسلاگ سئو')),
                ('sku', models.CharField(max_length=50, unique=True, verbose_name='کد کالا (SKU)')),
                ('summary', models.TextField(verbose_name='چکیده و معرفی کوتاه')),
                ('price', models.PositiveBigIntegerField(verbose_name='قیمت (تومان)')),
                ('compare_at_price', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='قیمت قبل از تخفیف (تومان)')),
                ('stock', models.PositiveIntegerField(default=10, verbose_name='موجودی انبار')),
                ('is_available', models.BooleanField(default=True, verbose_name='موجود برای خرید')),
                ('is_featured', models.BooleanField(default=False, verbose_name='محصول منتخب صفحه اصلی')),
                ('meta_title', models.CharField(blank=True, max_length=150, verbose_name='عنوان سئو')),
                ('meta_description', models.CharField(blank=True, max_length=250, verbose_name='توضیحات سئو')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.category', verbose_name='دسته\u200cبندی')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
                'ordering': ['-is_featured', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContentBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_type', models.CharField(choices=[('story', 'روایت اصالت و داستان محصول'), ('features', 'ویژگی\u200cها و نکات برجسته'), ('trust', 'تضمین کیفیت و اعتماد'), ('faq', 'پرسش\u200cهای متداول'), ('comparison', 'جدول مقایسه و انتخاب')], max_length=30, verbose_name='نوع بلوک')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان بلوک')),
                ('subtitle', models.CharField(blank=True, max_length=255, verbose_name='زیرعنوان')),
                ('content', models.TextField(verbose_name='محتوای متنی')),
                ('extra_data', models.JSONField(blank=True, default=dict, verbose_name='داده\u200cهای تکمیلی')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_blocks', to='catalog.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'بلوک محتوایی محصول',
                'verbose_name_plural': 'بلوک\u200cهای محتوایی محصولات',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(blank=True, max_length=500, verbose_name='آدرس تصویر')),
                ('alt_text', models.CharField(blank=True, max_length=200, verbose_name='متن جایگزین')),
                ('is_primary', models.BooleanField(default=False, verbose_name='تصویر اصلی')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'تصویر محصول',
                'verbose_name_plural': 'تصاویر محصول',
                'ordering': ['-is_primary', 'sort_order'],
            },
        ),
    ]
