# Generated by Django 5.0.14 on 2026-08-14 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_title', models.CharField(blank=True, max_length=200, verbose_name='عنوان سفارشی این محصول')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('content_block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_mappings', to='catalog.contentblock', verbose_name='بلوک محتوایی')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_block_links', to='catalog.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'نگاشت محصول و بلوک (ProductBlock)',
                'verbose_name_plural': 'نگاشت\u200cهای محصولات و بلوک\u200cها (ProductBlocks)',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
