# Generated by Django 5.0.14 on 2026-08-14 17:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_productblock'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='supply_cost',
            field=models.PositiveBigIntegerField(default=0, verbose_name='قیمت خرید از تأمین\u200cکننده (تومان)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='آخرین تغییر'),
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='نام کارگاه / تأمین\u200cکننده')),
                ('contact_name', models.CharField(max_length=100, verbose_name='نام مسئول')),
                ('phone', models.CharField(max_length=20, verbose_name='شماره تماس')),
                ('city', models.CharField(max_length=100, verbose_name='شهر / منطقه')),
                ('address', models.TextField(blank=True, verbose_name='نشانی کارگاه / مزرعه')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ عضویت')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_profile', to=settings.AUTH_USER_MODEL, verbose_name='حساب کاربری')),
            ],
            options={
                'verbose_name': 'تأمین\u200cکننده',
                'verbose_name_plural': 'تأمین\u200cکنندگان',
                'ordering': ['title'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='catalog.supplier', verbose_name='تأمین\u200cکننده'),
        ),
    ]
