# Generated by Django 5.0.14 on 2026-08-14 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_product_supply_cost_alter_product_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=150, verbose_name='نام خریدار')),
                ('author_phone', models.CharField(blank=True, max_length=20, verbose_name='شماره تماس')),
                ('order_number', models.CharField(blank=True, max_length=50, verbose_name='شماره سفارش مرتبط')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1 ستاره'), (2, '2 ستاره'), (3, '3 ستاره'), (4, '4 ستاره'), (5, '5 ستاره')], default=5, verbose_name='امتیاز (۱ تا ۵)')),
                ('comment', models.TextField(verbose_name='متن نظر و تجربه خرید')),
                ('is_approved', models.BooleanField(default=False, verbose_name='تأییدشده جهت نمایش عمومی')),
                ('is_verified_buyer', models.BooleanField(default=False, verbose_name='خریدار تأییدشده')),
                ('admin_reply', models.TextField(blank=True, verbose_name='پاسخ رسمی مدیریت ریهان')),
                ('replied_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان پاسخ ادمین')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='catalog.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'نظر محصول (M8)',
                'verbose_name_plural': 'نظرات و امتیازات محصولات',
                'ordering': ['-created_at'],
            },
        ),
    ]
