# Generated by Django 5.0.14 on 2026-08-14 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_productreview'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadCapture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=150, verbose_name='نام و نام خانوادگی')),
                ('phone', models.CharField(max_length=20, verbose_name='شماره موبایل')),
                ('requested_product_name', models.CharField(blank=True, max_length=200, verbose_name='عنوان کالای درخواستی')),
                ('notes', models.TextField(blank=True, verbose_name='توضیحات و ویژگی\u200cهای خاص')),
                ('status', models.CharField(choices=[('new', 'درخواست جدید'), ('in_progress', 'در حال پیگیری و گزینش تأمین\u200cکننده'), ('supplied', 'تأمین\u200cشده و اطلاع\u200cرسانی\u200cشده'), ('rejected', 'عدم امکان تأمین / بسته شده')], default='new', max_length=30, verbose_name='وضعیت پیگیری')),
                ('admin_notes', models.TextField(blank=True, verbose_name='یادداشت و اقدامات ادمین')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='catalog.product', verbose_name='محصول ناموجود کاتالوگ')),
            ],
            options={
                'verbose_name': 'سرنخ / درخواست محصول (M9)',
                'verbose_name_plural': 'سرنخ\u200cها و درخواست\u200cهای محصولات',
                'ordering': ['-created_at'],
            },
        ),
    ]
